### ISSUE TITLE
Wemos-IASLoader:90:70: error: 'chipId' is not captured

### ISSUE THREAD

**Issue by 877dev** [iotappstory/ESP-Library#100]
Arduino IDE 1.8.8
ESP-Library-2.0.1
Wemos D1 mini (genuine)

Getting the following error when verifying:

  **C:\Program Files (x86)\Arduino\libraries\ESP-Library-2.0.1\examples\Wemos\Wemos-IASLoader\Wemos-IASLoader.ino: In lambda function:

  Wemos-IASLoader:90:70: error: 'chipId' is not captured

dispTemplate_threeLineV2(F("Connect to"), F("Wi-Fi"), "xxxxx-" + chipId);

   exit status 1
   'chipId' is not captured**

**Comment by CwlBroeders** [comment]
the sketch is running into a problem on  the following code (line 90 in the example sketch)

  IAS.onConfigMode([]() {
    dispTemplate_threeLineV2(F("Connect to"), F("Wi-Fi"), "xxxxx-" + chipId);
  });

the chipId is used to make a unique SSID (handy in classroom situations to recognise the correct SSID to connect to) 
for now u can remove the chipId in the sketch where it is used, iirc this problem should be fixed in the next library update
